# Generated by Django 3.1.1 on 2022-06-25 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_basica_pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review_pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('comentario', models.CharField(max_length=500)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pelicula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pelicula.peliculas')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula_iden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pelicula.peliculas')),
                ('playlist_iden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pelicula.playlist_basica_pelicula')),
            ],
        ),
    ]
